# Generated by Django 5.1.4 on 2025-03-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('michaelScore', models.IntegerField()),
                ('michaelTeam', models.CharField(max_length=5)),
                ('geoScore', models.IntegerField()),
                ('geoTeam', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quit', models.BooleanField(default=False)),
                ('winner', models.CharField(max_length=5)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.details')),
            ],
        ),
    ]
