# Generated by Django 5.1.4 on 2025-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='geoScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='michaelScore',
            field=models.IntegerField(default=0),
        ),
    ]
